### ISSUE TITLE
Lens and GitHub sync not working

### ISSUE THREAD

**Issue by bigint** [guildxyz/guild.xyz#1028]
### Describe the bug

https://guild.xyz/heyxyz
https://twitter.com/yogicodes/status/1748998899480539182

### To Reproduce

You can check in this guild https://guild.xyz/heyxyz if you joined

### Expected Behavior

It should sync

### Which browser are you using? (if relevant)

Chrome

**Comment by sasicodes** [comment]
Same for Tape - https://guild.xyz/tape

**Comment by Lacc1986** [comment]
I expereince the following error while I trying to connect with Lens: Error: /data/minAmount must be number

**Comment by foolo** [comment]
![Screenshot_2024-03-22_14-56-32](https://github.com/guildxyz/guild.xyz/assets/667227/68b65923-8fab-4d8a-b878-da9bf1d394f4)
![Screenshot_2024-03-22_14-57-24](https://github.com/guildxyz/guild.xyz/assets/667227/23e693a8-3a5e-496c-8f07-a771a1a636bc)

**Comment by BrickheadJohnny** [comment]
Hello @bigint, @sasicodes, @Lacc1986, @foolo, we've just released an update (started using Lens v2 API), so this issue should be solved now!

**Comment by foolo** [comment]
Still maybe a bit out of sync with the API or something?
For example, I have been following @sagargowda for a while, but it still says i don't follow, even after refreshing:
![image](https://github.com/guildxyz/guild.xyz/assets/667227/58b030ae-5af2-416b-9f7d-0316c3a189f8)
(my handle is @olofand47635618 , i have made sure that i'm looking at the correct handle)

**Comment by BrickheadJohnny** [comment]
> Still maybe a bit out of sync with the API or something? For example, I have been following [sagargowda](https://www.lensfrens.xyz/sagargowda) for a while, but it still says i don't follow, even after refreshing: ![Screenshot_2024-04-22_14-41-23 (copy 1)](https://private-user-images.githubusercontent.com/667227/324463337-da43789b-3700-4ae2-b5e9-798da4c36200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTAyNDYsIm5iZiI6MTcxMzc4OTk0NiwicGF0aCI6Ii82NjcyMjcvMzI0NDYzMzM3LWRhNDM3ODliLTM3MDAtNGFlMi1iNWU5LTc5OGRhNGMzNjIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjQ1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmQxY2ZhYTY3NTY2YWNiMTdjMjllYWRjZGMyZDhjMzI1MDY0YTMwYjI2ZDA1ZGYwNzM0YjM4YzhiMGY1YzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rMbOEETTY5XEOf8cikRo6jRClKBCYBO0qsvvBDaPxO0)
> 
> (my handle is [@olofand47635618](https://www.lensfrens.xyz/olofand47635618) , I have made sure that i'm looking at the correct handle)

Have you clicked on the refresh icon? We don't re-check accesses automatically anymore, so you'll need to click on that. If it still says incorrect data, we'll make sure to investigate ASAP! 
![image](https://github.com/guildxyz/guild.xyz/assets/92519134/829132be-328f-4d66-b7b4-bfbffe811f26)

**Comment by foolo** [comment]
> > Still maybe a bit out of sync with the API or something? For example, I have been following [sagargowda](https://www.lensfrens.xyz/sagargowda) for a while, but it still says i don't follow, even after refreshing: ![Screenshot_2024-04-22_14-41-23 (copy 1)](https://private-user-images.githubusercontent.com/667227/324463337-da43789b-3700-4ae2-b5e9-798da4c36200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTAyNDYsIm5iZiI6MTcxMzc4OTk0NiwicGF0aCI6Ii82NjcyMjcvMzI0NDYzMzM3LWRhNDM3ODliLTM3MDAtNGFlMi1iNWU5LTc5OGRhNGMzNjIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjQ1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmQxY2ZhYTY3NTY2YWNiMTdjMjllYWRjZGMyZDhjMzI1MDY0YTMwYjI2ZDA1ZGYwNzM0YjM4YzhiMGY1YzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rMbOEETTY5XEOf8cikRo6jRClKBCYBO0qsvvBDaPxO0)
> > (my handle is [@olofand47635618](https://www.lensfrens.xyz/olofand47635618) , I have made sure that i'm looking at the correct handle)
> 
> Have you clicked on the refresh icon? We don't re-check accesses automatically anymore, so you'll need to click on that. If it still says incorrect data, we'll make sure to investigate ASAP! ![image](https://private-user-images.githubusercontent.com/92519134/324464982-829132be-328f-4d66-b7b4-bfbffe811f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTA3ODIsIm5iZiI6MTcxMzc5MDQ4MiwicGF0aCI6Ii85MjUxOTEzNC8zMjQ0NjQ5ODItODI5MTMyYmUtMzI4Zi00ZDY2LWI3YjQtYmZiZmZlODExZjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEyNTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNGY4MjE1MTM4ZWEyOTExZWRkNWJhNzc3ZjdmNmQxZDQyNzRkNGQwODU3ZjBhYzFmZDZhZGFhNzc0ZmM4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PacOZjxp138mrTTzUS9oWZLHiXI47wPoV1njsiH_uNA)

Yes, (as I wrote ;) ) It says "Successfully updated role access" and "1/2 requirements satisfied".
![Screenshot_2024-04-22_15-01-09](https://github.com/guildxyz/guild.xyz/assets/667227/800c182c-4061-4ce1-8167-bbd16ba4ee77)

**Comment by BrickheadJohnny** [comment]
Hey @foolo we've identified the issue: seems like you indeed follow this user, but you haven't minted the follow NFT. We'll make sure that everyone gets access who actually follows a specific user. Thanks for your report, will make sure to ping you here once our update goes live!

(We use the API for some of the Lens requirements, but we actually check onchain data for the "Follow ... on Lens Protocol" requirement type)

**Comment by foolo** [comment]
@BrickheadJohnny I see, thanks for looking into it!

**Comment by marclllaks** [comment]
Hey @foolo it should be fixed now, please check if it's working for you

**Comment by foolo** [comment]
> Hey @foolo it should be fixed now, please check if it's working for you

It is! Thanks a lot!

![Screenshot_2024-04-23_14-45-08](https://github.com/guildxyz/guild.xyz/assets/667227/0ca5801b-2180-4a38-80e3-c2c809951b93)
