### ISSUE TITLE
Bug while trying to connect Twitter and Typo in the error shown

### ISSUE THREAD

**Issue by NickTheGrizzly** [guildxyz/guild.xyz#1087]
### Describe the bug

When trying to reconnect Twitter it gave an error. Also Authentication is spelled wrong in the error that comes up. Image below.
![image](https://github.com/guildxyz/guild.xyz/assets/118949684/dad0495b-e56b-40de-9475-79f616b9f189)

### To Reproduce

Have Twitter lose connection, then attempt to reconnect a Twitter account

### Expected Behavior

To connect and sync to Twitter account.

### Which browser are you using? (if relevant)

Brave

**Comment by Mikanoshi** [comment]
Same issue, same error, same guild :)

**Comment by BrickheadJohnny** [comment]
Hello @NickTheGrizzly, @Mikanoshi & @vigates, thank you for the reports! We're unfortunately rate limited by X - we're working on it, hopefully the issue will be resolved later today.

> same here guild.xyz, and i cant login with metamask??

@vigates you may not see the "MetaMask" button if you're using another injected wallet, like Brave Wallet or OKX. If you still think that there's an issue with MetaMask, please provide us more details and we'll look into it.

**Comment by vigates** [comment]
appreciated the guidance @BrickheadJohnny, i can access to my account which is linked to MM now. But I have to remove my OKX wallet extension, will it override and log me out again, if i set my OKX wallet back up?

**Comment by BrickheadJohnny** [comment]
> appreciated the guidance @BrickheadJohnny, i can access to my account which is linked to MM now. But I have to remove my OKX wallet extension, will it override and log me out again, if i set my OKX wallet back up?

Great!
It probably won't really work if you re-enable the OKX extension. We'll make sure to release a fix for this issue in the upcoming weeks.

**Comment by Maxpaynecrypto** [comment]
Also having the same issue here!

**Comment by sathsarasupunb** [comment]
Same

**Comment by matstawski** [comment]
Same here

**Comment by luizender** [comment]
same here

**Comment by uthredrganarsoon** [comment]
still same issue trying million time

**Comment by xinguy** [comment]
Same here i have been trying for 24 hours
![2024-02-28_17-05-45](https://github.com/guildxyz/guild.xyz/assets/111216663/43c993b7-3dda-4293-9ff9-6e9d679ff517)

**Comment by Lacc1986** [comment]
same

**Comment by BrickheadJohnny** [comment]
We've reworked this since these reports, so it should work properly. Closing this, but feel free to report any new issues!
