### ISSUE TITLE
Can not setup in local machine

### ISSUE THREAD

**Issue by oneforalone** [guildxyz/guild.xyz#1102]
Some changes regarding the SDK installation workflow:
- The `WAAS_WEB_URL` and `WAAS_VIEM_URL` env vars have to be defined in `.env.local`
   - Value is available on 1Password, and from Vercel
- If the env vars are defined, it is enough to run `npm i`, which will trigger the `postinstall` script, which installs the SDK-s if the env vars are defined correctly
   - Everyone within the org will get the env vars
- For external developers, who don't have the env vars, running `git apply no_waas.diff` should make the appropriate changes, so the app can be built without the SDKs
   - We could also just run a `git revert` for the PR's squashed commit
   - These git-based solutions might run into conflicts later on, but hopefully the SDKs get published on NPM soon enough, so it might not cause problems

_Originally posted by @cs-balazs in https://github.com/guildxyz/guild.xyz/issues/1015#issuecomment-1908302579_

**Comment by oneforalone** [comment]
I can not make it on my macbook m2 cause `git apply no_waas.diff` no working, it complains:
```
error: patch failed: src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts:1
error: src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx:32
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/GoogleLoginButton.tsx:1
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/GoogleLoginButton.tsx: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/components/CopyCWaaSBackupData.tsx:1
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/components/CopyCWaaSBackupData.tsx: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/components/UserOnboardingModal.tsx:1
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/components/UserOnboardingModal.tsx: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/hooks/useLoginWithGoogle.ts:1
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/hooks/useLoginWithGoogle.ts: patch does not apply
error: patch failed: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/utils/googleDrive.ts:1
error: src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/utils/googleDrive.ts: patch does not apply
error: patch failed: src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx:19
error: src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx: patch does not apply
error: patch failed: src/connectors.ts:1
error: src/connectors.ts: patch does not apply
```
I thinks this is caused by coinbase not release their lib, but i believe that `git apply no_waas.diff` should work. Unfortunately, it doesn't. Seems that the only way to run it on local machine it to revert before #1015 , but that's kinda wired.

**Comment by cs-balazs** [comment]
Thanks for the report @oneforalone!
Opened a PR with an alternative solution here: https://github.com/guildxyz/guild.xyz/pull/1104

**Comment by oneforalone** [comment]
> Opened a PR with an alternative solution here: #1104

It now works with  PR #1104 , so i'm gonna to close it, and it would work after PR merged. Really appreciate for your quick response.
