### ISSUE TITLE
Fail to Connect Discord and no response

### ISSUE THREAD

**Issue by BenZCryptoEngineer** [guildxyz/guild.xyz#1163]
### Describe the bug

Try to connect to Discord, but nothing happened, no response at all.

![image](https://github.com/guildxyz/guild.xyz/assets/8150480/bd11f794-682d-49a7-a810-605b5cc47ce0)

### To Reproduce

Go the any Guild page, and try to connect the discord

### Expected Behavior

Can successfully connected

### Which browser are you using? (if relevant)

Chorme Version 123.0.6312.122 (Official Build) (64-bit)

**Comment by BrickheadJohnny** [comment]
Hello, please double check if your browser blocks pop-up windows. We'd normally show the Discord auth window in a pop-up, so I guess you use some kind of extension/setting which breaks this behavior.

**Comment by BenZCryptoEngineer** [comment]
Hi @BrickheadJohnny , I double check the extension, and even the Adblock is turned off.
![image](https://github.com/guildxyz/guild.xyz/assets/8150480/16a947f5-dd55-4c32-85b8-d50965af8f1d)

When clicking the button, nothing showed up in my network, the request is not sent at all
![image](https://github.com/guildxyz/guild.xyz/assets/8150480/86bcd4ee-b7b4-43fd-b716-5367d9a55feb)
