### ISSUE TITLE
Excessive full page rerendering caused by `Layout` component

### ISSUE THREAD

**Issue by dominik-stumpf** [guildxyz/guild.xyz#1202]
### Describe the bug

> [!NOTE] 
> `Layout` refers to component at [`/src/components/common/Layout/Layout.tsx`](https://github.com/guildxyz/guild.xyz/blob/da0cf25bdab18cf70c34bba0349420c60eb51fb3/src/components/common/Layout/Layout.tsx)

There is an ongoing issue with page route `/create-guild` at the moment where full sized page rerenders are occurring when updating form fields or progressing through the guild creation process as shown in the reproduction video.

As a result this introduces performance issues where form validations are happening, severely damaging the end user experience of newcomers and regular users, especially the ones with low-end devices.

After investigating, I found that problem is located in the widely used `Layout` component which could make this issue touch other areas of the website and overall this is not a good practice in react. The performance problem will grow as this component does making the site less and less usable.

### To Reproduce

https://github.com/guildxyz/guild.xyz/assets/122315398/25c65e8b-da0a-44a4-a19b-138931de3385

React dev tools highlights with the rectangles how areas like the `Header` is being rerendered on every keystroke, interaction abundantly.

### Expected Behavior

Should strictly rerender only components that use the relevant input value.

### Which browser are you using? (if relevant)

Browser irrelevant.

**Comment by dominik-stumpf** [comment]
If you don't mind I would like to open a discussion or PR about this issue soon.

**Comment by BrickheadJohnny** [comment]
Hey, thanks for the detailed report. We should definitely fix it, feel free to open a PR if you wish @dominik-stumpf!

**Comment by BrickheadJohnny** [comment]
Issue fixed in #1205
