### ISSUE TITLE
Wallet not connecting 

### ISSUE THREAD

**Issue by AJCRYPTO007** [guildxyz/guild.xyz#1576]
### Describe the bug

From capy bara we have a task to sign with guilt.xyz but we are processing with onchain wallet is time taker and not connecting after two methods

### To Reproduce

Bug

### Expected Behavior

Connect fast

### Which browser are you using? (if relevant)

Crome

**Comment by Laurensavage** [comment]
> ### Describe the bug
> From capy bara we have a task to sign with guilt.xyz but we are processing with onchain wallet is time taker and not connecting after two methods
> 
> ### To Reproduce
> Bug
> 
> ### Expected Behavior
> Connect fast
> 
> ### Which browser are you using? (if relevant)
> Crome


Hello @AJCRYPTO007 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID CHI13368
Please see the link below to our dedicated support line:
[Onchain Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Vickynicole** [comment]
Hello @AJCRYPTO007 
That sounds like a hassle. Maybe there's a compatibility issue with guilt.xyz and your onchain wallet. I'll have to refer you to the official support live chat with the ticket ID CHI07638
Please see the link below to our dedicated support line:
[Onchain Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
