### ISSUE TITLE
Add eligible guilds

### ISSUE THREAD

**Issue by meirbank** [guildxyz/guild.xyz#405]
Hi team,

My background: I'm an early investor in Agora with AngelDAO. AngelDAO offers development support to portfolio projects, we have a long track record there. 

The idea: I discussed this with RAZ on discord, I want to make a PR to implement this: https://twitter.com/cjliu49/status/1528134518850301953

So in between "Your guilds" and "All guilds" I would put "Eligible guilds" and display whatever guilds the user is eligible to join based on the contents of their wallet.

I can get started on this and have it completed in a few days, before the end of the weekend. Let me know if all sounds good!

**Comment by dovalid** [comment]
Hey Meir, happy to see you here!

An eligible guilds section would be so awesome but unfortunately I don't think it's technically feasible right now. Checking access is the most difficult & resource intensive thing we do, checking it for all guilds would likely take for hours.

Only checking based on basic ERC20/721/1155 requirements feels realistic tho: we should make a backend endpoint like `/guild/address/eligible`, fetch the address's assets with balancy, filter guilds that have any requirement with those assets, and only check access for those.

Do you still wanna give it a shot this way? Our backend is not open-source yet but we'll add you then!
